include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - '**/*.gr.dart'
    - '**/translations**/*.dart'

  errors:
    invalid_annotation_target: ignore
