name: space_flight_news
description: Space Flight News
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  auto_route: 5.0.1
  dio: 4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 2.1.0
  get_it: 7.2.0
  i69n: 2.1.0
  injectable: 1.5.3
  intl: 0.17.0
  json_annotation: 4.6.0
  retrofit: 3.0.1+1
  url_launcher: 6.1.5

dev_dependencies:
  auto_route_generator: 5.0.2
  build_runner: 2.2.0
  injectable_generator: 1.5.4
  flutter_gen_runner: 4.3.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.1.0+1
  json_serializable: 6.3.1
  retrofit_generator: 4.0.3+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/presentation/assets
  assets:
    package_parameter_enabled: true
